### ISSUE TITLE
»format_on_save« breaks history

### ISSUE THREAD

**Issue by leonklingele** [dericofilho/sublime-phpfmt#89]
Let's say you have a file that looks like this:
```
<?php

if (true) {
	// Hello World
}
```

1. Save.
2. Add `echo 'Test';` between the curly brackets.
3. Save again.
4. CMD (Mac) + z to undo.
5. Save once again.

Now you can't undo the undo (i.e. re-add the `echo ..` using CMD + shift + z).
Can this even be fixed?

**Comment by dericofilho** [comment]
@leonklingele It works on my Machine (TM). Therefore, I will need more context from your configuration, namely:
- Sublime Text version (including build number)
- Plugin list
- Ideally a screen record showing that as much as you can, including call the same command several times. 

I tried both undo and redo, and worked fine for me.

**Comment by leonklingele** [comment]
- OS X Yosemite – 10.10.2 (14C109)
- Sublime Text 3 Build 3065
- Screen Recording (I explained every keyboard shortcut used): https://www.leonklingele.de/sublime-phpfmt.mp4

sublime-phpfmt configuration:
```
{
	"autocomplete": false,
	"autoimport": true,
	"autopreincrement": false,
	"comment_auto_align": false,
	"disable_auto_align": true,
	"enable_auto_align": false,
	"format_on_save": true,
	"linebreak_after_namespace": true,
	"linebreak_between_methods": true,
	"merge_else_if": true,
	"php_bin": "/usr/local/bin/php",
	"psr1": false,
	"psr2": false,
	"remove_leading_slash": true,
	"restore_comments": true,
	"short_array": false,
	"smart_linebreak_after_curly": true,
	"version": 1,
	"vet": false,
	"visibility_order": true,
	"yoda": false
}
```

**Comment by dericofilho** [comment]
@leonklingele could you please give a plugin list? I want to rule out the possibility of being an interaction with some other plugin.

**Comment by leonklingele** [comment]
Sure! Enabled plugins:
- AdvancedNewFile
- ApplySyntax
- Autoprefixer
- BracketHighlighter
- Clickable URLs
- Closure
- ColorPicker
- Diff
- Emmet
- File History
- FileDiffs
- Function Name Display
- GitGutter
- GoLint
- GutterColor
- SublimeCodeIntel
- SublimeLinter
- phpfmt

**Comment by dericofilho** [comment]
@leonklingele I appreciate your answer. I will investigate and try to fix this ASAP.

**Comment by leonklingele** [comment]
Same results if only phpfmt is enabled: Can't 'redo'.
Everything works fine if `format_on_save` is set to false; But manually formatting is such a pain.. :cry:

**Comment by dericofilho** [comment]
@leonklingele Thanks for the extra information. I believe I managed to isolate the problem. It seems that the file revert call I make to reload the file is generating this issue. I am checking how other plugins, such GoSublime, handle this.

**Comment by dericofilho** [comment]
@leonklingele please, update manually to https://github.com/dericofilho/sublime-phpfmt/commit/1ca344885d4e5e154be8ecd3a2a28725d7b6300d and test. It should be fixed.

**Comment by leonklingele** [comment]
*Sometimes* I can »redo« changes after saving a file, sometimes »redo« still doesn't work.
Also it now takes around 2 seconds to format a file, is this normal?

1ca3448 introduced an issue:
When reformatting the file manually using "phpfmt: format now", this popup shows up:
https://s.leonklingele.de/1423988741
After clicking »reload« all changes made to the file since it was saved last time are reverted.

I can provide a screen recording if you want.
Thanks for helping.

**Comment by dericofilho** [comment]
@leonklingele thanks for the feedback. I am going to work more on this.

**Comment by dericofilho** [comment]
@leonklingele please, update manually to https://github.com/dericofilho/sublime-phpfmt/commit/e5886640f21109407cc95ef4bd940f78a1b53604 and test. 

I used a different strategy that should work better.

**Comment by leonklingele** [comment]
With e588664 every time I save a file, the cursor jumps to the first line of the file.
Also CMD + shift + z (redo) doesn't work.

**Comment by dericofilho** [comment]
@leonklingele thanks for the feedback. I am going to work more on this.

**Comment by dericofilho** [comment]
@leonklingele please, provide a screencast of the cursor going to the first line. I could not reproduce this behavior.

**Comment by dericofilho** [comment]
@leonklingele Please, update manually to https://github.com/dericofilho/sublime-phpfmt/commit/4dcf76538546600ea2e04c2a976b625e80afb936 and test.

I used a similar strategy from GoSublime. If the redo works with Go files, it should work with sublime-phpfmt.

**Comment by leonklingele** [comment]
Awesome! Redo finally works *every time*!
Also the cursor doesn't jump anymore.

Still one little issue which seems to have been introduced by the `different-reload` branch:
Sometimes, after automatically formatting, the file-modification indicator of Sublime stays orange: https://s.leonklingele.de/1424039089
Try it with this Sublime preference: `"highlight_modified_tabs": true`
This always happens if phpfmt has to do some formatting on the content.

**Comment by dericofilho** [comment]
@leonklingele thanks for the feedback. I am going to work more on this problem of marking the file as needing change.

**Comment by dericofilho** [comment]
@leonklingele please, make a backup of your configuration files and manually update to https://github.com/dericofilho/sublime-phpfmt/commit/6ab3a09defda3c814b4dff51bc212353344c3392.

It should solve the file modification indicator bug.

**Comment by leonklingele** [comment]
Yup, everything seems to work fine now.
I will test extensively today and get back to you tomorrow.
Thank you for your support.

**Comment by leonklingele** [comment]
Thank you for your tremendous support. Closing now.

**Comment by dericofilho** [comment]
@leonklingele Thanks for using the plugin. Regards.
